#!/bin/sh

vim13="$HOME/vim13"

if [ ! -d $vim13 ]; then
  echo "Installing vim13"
  git clone https://github.com/ernestas-poskus/vim13.git $vim13
fi

mkdir -p $HOME/.vim/autoload > /dev/null 2>&1
mkdir -p $HOME/.vim/colors > /dev/null 2>&1
mkdir -p $HOME/.vim/undodir > /dev/null 2>&1
mkdir -p $HOME/.vim/colors > /dev/null 2>&1
mkdir -p $HOME/.vim/after

# Vim plugin manager
curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Molokai Color scheme
curl -fLo $HOME/.vim/colors/molokai.vim --create-dirs \
    https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim

# Zenburn Color scheme
curl -fLo $HOME/.vim/colors/zenburn.vim --create-dirs \
    https://raw.githubusercontent.com/jnurmine/Zenburn/master/colors/zenburn.vim

ln -sf $vim13/languages/ $HOME/.vim/after/ftpugin/*
ln -sf $vim13/vimrc $HOME/.vimrc

# Support NEOVIM
ln -sf $vim13/vimrc $HOME/.nvimrc
ln -sf $HOME/.vim $HOME/.nvim

# Link NEOVIM config
mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
ln -s $HOME/.vim $XDG_CONFIG_HOME/nvim
ln -s $HOME/.vimrc $XDG_CONFIG_HOME/nvim/init.vim
