#!/bin/sh

vim13="$HOME/vim13"

if [ ! -d $vim13 ]; then
  echo "Installing vim13"
  git clone https://github.com/ernestas-poskus/vim13.git $vim13
fi

mkdir -p $HOME/.vim/autoload > /dev/null 2>&1
mkdir -p $HOME/.vim/colors > /dev/null 2>&1
mkdir -p $HOME/.vim/undodir > /dev/null 2>&1
mkdir -p $HOME/.vim/colors > /dev/null 2>&1
mkdir -p $HOME/.vim/after

# Vim plugin manager
curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Molokai Color scheme
curl -fLo $HOME/.vim/colors/molokai.vim --create-dirs \
    https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim

# Zenburn Color scheme
curl -fLo $HOME/.vim/colors/zenburn.vim --create-dirs \
    https://raw.githubusercontent.com/jnurmine/Zenburn/master/colors/zenburn.vim

# Bluewery Color scheme
curl -fLo $HOME/.vim/colors/bluewery.vim --create-dirs \
  https://raw.githubusercontent.com/relastle/bluewery.vim/master/autoload/lightline/colorscheme/bluewery.vim

# Anderson Color scheme
curl -fLo $HOME/.vim/colors/anderson.vim --create-dirs \
  https://raw.githubusercontent.com/tlhr/anderson.vim/master/colors/anderson.vim

ln -sf $vim13/languages $HOME/.vim/after/ftplugin
ln -sf $vim13/vimrc $HOME/.vimrc

# Support NEOVIM
ln -sf $vim13/vimrc $HOME/.nvimrc
ln -sf $HOME/.vim $HOME/.nvim

# Link NEOVIM config
mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
ln -s $HOME/.vim $XDG_CONFIG_HOME/nvim
ln -s $HOME/.vimrc $XDG_CONFIG_HOME/nvim/init.vim

echo 'Installing ag:'
if ! which ag  > /dev/null; then
  sudo dnf install the_silver_searcher
fi

if ! which fzy  > /dev/null; then
  echo 'Installing fzy fuzzy finder'
  install_path='/tmp/fzy'
  git clone https://github.com/jhawthorn/fzy.git $install_path
  cd $install_path && sudo make install
fi
